
# nome completo del modello
NOME_COMPLETO_MODELLO : "best.pth"

# path delle cartelle con i dati da classificare
BASE_PATH_DATI_CLASSIFICAZIONE : "/home/riccardo/Focus/22==Esperimenti/Anno2020/Articolo Workshop ICPR/dataset/train"

# path della architettura della rete
PATH_ARCHITETTURA_MODELLO : "/home/riccardo/git-sw/ann_modelli_importati/inceptionresnetv2_nuova/"

# nome file di output per la matrice di confusione
NOME_MATRICE_CONFUSIONE : "matrice_confusione.csv"